"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

x1, x2, n, s = 1, 2, 0, 2
fibonacci = [x2]
total = 4000000
while n < total:
    n = x1 + x2
    x1, x2 = x2, n
    # fibonacci.append(n)
    if n % 2 == 0 and n < total:
        fibonacci.append(n)
        s += n
print(fibonacci)
print(s)

# 4613732